name: CD - Production Deployment

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  release:
    types: [published]
  workflow_dispatch:  # Allow manual triggering

# Ensure only one deployment runs at a time
concurrency:
  group: production-deployment
  cancel-in-progress: true

env:
  NODE_VERSION: '20.x'
  DEPLOY_TIMEOUT_MIN: 15

jobs:
  pre-deployment-checks:
    name: Pre-deployment validation
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check-changes.outputs.should_deploy }}
      commit_sha: ${{ github.sha }}
      commit_message: ${{ github.event.head_commit.message }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for relevant changes
        id: check-changes
        run: |
          # Skip deployment if only documentation changed
          if git diff --name-only HEAD^ HEAD | grep -qvE '(.md$|^docs/)'; then
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          else
            echo "should_deploy=false" >> $GITHUB_OUTPUT
            echo "🔄 Only documentation changes detected, skipping deployment"
          fi

      - name: Verify tag if release
        if: github.event_name == 'release'
        run: |
          if [[ ! "${{ github.event.release.tag_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.-]+)?$ ]]; then
            echo "❌ Invalid tag format: ${{ github.event.release.tag_name }}"
            exit 1
          fi

  deploy:
    name: Deploy to Production
    needs: pre-deployment-checks
    if: needs.pre-deployment-checks.outputs.should_deploy == 'true'
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://vpn.mangoapp.com  # Your VPN service URL

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.sha }}

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --audit=false --fund=false
      env:
        NODE_ENV: production

    - name: Run security audit
      run: |
        npm audit --production --audit-level=high
        # Continue despite audit findings (adjust based on your policy)
      continue-on-error: true

    - name: Run tests
      run: npm run test:ci
      env:
        CI: true
        NODE_ENV: test

    - name: Build application
      run: npm run build:prod
      env:
        NODE_ENV: production

    - name: Verify build integrity
      run: |
        # Check that essential VPN files were built
        if [ ! -f "dist/vpn-client" ] && [ ! -f "dist/index.js" ]; then
          echo "❌ Build failed: missing essential VPN files"
          exit 1
        fi
        
        # Generate checksum for verification
        find dist/ -type f -name "*" -exec sha256sum {} \; > dist-checksums.txt
        echo "✅ Build integrity verified"

    - name: Create deployment package
      run: |
        tar -czf mango-vpn-deploy-${{ github.sha }}.tar.gz \
          dist/ \
          package.json \
          package-lock.json \
          config/production.json \
          dist-checksums.txt
        echo "📦 Deployment package created"

    - name: Deploy to production servers
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
        SOURCE: mango-vpn-deploy-${{ github.sha }}.tar.gz
        EXCLUDE: "/node_modules/, /test/, /docs/"
        SCRIPT_BEFORE: |
          echo "🚀 Starting Mango VPN deployment"
          echo "Deploying commit: ${{ github.sha }}"
          # Backup current deployment
          tar -czf /tmp/mango-vpn-backup-$(date +%Y%m%d-%H%M%S).tar.gz ${{ secrets.REMOTE_TARGET }}/current
        SCRIPT_AFTER: |
          # Extract and verify deployment
          tar -xzf mango-vpn-deploy-${{ github.sha }}.tar.gz -C ${{ secrets.REMOTE_TARGET }}/releases/${{ github.sha }}
          cd ${{ secrets.REMOTE_TARGET }}/releases/${{ github.sha }}
          
          # Verify checksums
          sha256sum -c dist-checksums.txt
          
          # Install production dependencies
          npm ci --production --audit=false
          
          # Update symlink
          ln -sfn ${{ secrets.REMOTE_TARGET }}/releases/${{ github.sha }} ${{ secrets.REMOTE_TARGET }}/current
          
          # Restart VPN services
          systemctl restart mango-vpn || echo "Service restart may require manual intervention"
          
          # Cleanup old deployments (keep last 5)
          ls -dt ${{ secrets.REMOTE_TARGET }}/releases/* | tail -n +6 | xargs rm -rf
          
          echo "✅ Mango VPN deployment completed successfully"

    - name: Verify deployment health
      run: |
        # Add health check for VPN services
        echo "Running post-deployment health checks..."
        # This would typically curl your health endpoint
        echo "Health checks completed"

    - name: Notify deployment status
      uses: actions/github-script@v6
      with:
        script: |
          const { data: commit } = await github.rest.repos.getCommit({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: context.sha
          });
          
          const shortSha = context.sha.substring(0, 7);
          const commitMessage = commit.commit.message.split('\n')[0];
          
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `✅ Production Deployment Successful - ${shortSha}`,
            body: `## Mango VPN Deployment Complete
**Status:** ✅ Success  
**Commit:** ${context.sha}  
**Message:** ${commitMessage}  
**Deployed at:** ${new Date().toISOString()}  
**Environment:** Production  
**Triggered by:** ${context.actor}  
**Duration:** ${(Date.now() - new Date(context.payload.head_commit.timestamp).getTime()) / 1000}s

### Next Steps:
- [ ] Verify VPN connectivity
- [ ] Test authentication flow
- [ ] Monitor error rates
- [ ] Check performance metrics

### Rollback:
If issues are detected, rollback to previous deployment:
\`\`\`bash
cd ${process.env.REMOTE_TARGET}
ln -sfn \$(ls -dt releases/* | head -2 | tail -1) current
systemctl restart mango-vpn
\`\`\`
`
          });

    - name: Send deployment notification
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        channel: '#deployments'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  post-deployment:
    name: Post-deployment validation
    needs: deploy
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Check deployment status
        run: |
          if ${{ needs.deploy.result }} == 'success'; then
            echo "✅ Deployment completed successfully"
          else
            echo "❌ Deployment failed"
            exit 1
          fi

      - name: Run smoke tests
        run: |
          # Add basic smoke tests to verify VPN functionality
          echo "Running post-deployment smoke tests..."
          # Example: curl -f https://vpn.mangoapp.com/health
          echo "Smoke tests completed"
