name: Issue Automation

on:
  issues:
    types: [opened, edited, labeled]
  issue_comment:
    types: [created]

jobs:
  issue-triage:
    runs-on: ubuntu-latest
    steps:
      - name: Check for missing information in new issues
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue
            if (!issue.body.includes('## Environment') || !issue.body.includes('## Steps to Reproduce')) {
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: ['needs-info']
              })
              
              github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: '👋 Thank you for reporting this issue! Please provide the requested environment details and reproduction steps to help us investigate.'
              })
            }

  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-label issues based on title
        uses: actions/github-script@v6
        with:
          script: |
            const title = context.payload.issue.title.toLowerCase()
            const labels = []
            
            if (title.includes('bug') || title.includes('error') || title.includes('fix')) {
              labels.push('bug')
            }
            if (title.includes('feat') || title.includes('feature') || title.includes('enhancement')) {
              labels.push('enhancement')
            }
            if (title.includes('doc') || title.includes('documentation')) {
              labels.push('documentation')
            }
            
            if (labels.length > 0) {
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                labels: labels
              })
            }
