name: Nightly Builds

on:
  schedule:
    - cron: '0 2 * * *' # Daily at 2 AM
  workflow_dispatch:

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Run extended tests
        run: npm run test:ci -- --coverage

      - name: Build all targets
        run: npm run build:all

      - name: Upload nightly build
        uses: actions/upload-artifact@v3
        with:
          name: nightly-build-${{ github.sha }}
          path: dist/
          retention-days: 7
