name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate PR title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for large files
      uses: htorodriguez/devops-pr-tools@v1
      with:
        tool: 'check-large-files'
        args: '--max-size 5MB'

    - name: Check commit messages
      uses: "wagoid/commitlint-github-action@v5"
